### PR TITLE
[WIP] Initial version

### PR DESCRIPTION
**Pull request by MorrisJobke**

### CODE REVIEW

**Comment by mar1u5** [comment]
🎆 ... I'm just missing the license headers 😁

**Comment by MorrisJobke** [comment]
> 🎆 ... I'm just missing the license headers 😁

WIP ;)

**Comment by mar1u5** [comment]
I will give it a first try this afternoon.

**Comment by MorrisJobke** [comment]
Try it with minio.io ;) but there is a bug with the credentials that need to be resolver before...so don'twaste time here...I can pi g you once it is ready for testing :)

**Comment by mar1u5** [comment]
Any news here? :grin: @MorrisJobke

**Comment by MorrisJobke** [comment]
> Any news here? 😁 @MorrisJobke

This was moved to https://github.com/nextcloud/server/pull/768

**Pull request closed without merging**
